# fly.toml app configuration file generated for cwy-short-pj-25-09 on 2025-09-18T11:17:43+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cwy-short-pj-25-09'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
